@startsalt

{

View/Edit Hours

{#
Employee code | Last name | First name | Pay rate | Shift start date | Shift start time | Shift end time | Casual Loading
S1065 | Doe | John | 25.75 | 14/09/2023 | 09:00 | 17:00 | Y
S1065 | Doe | John | 25.75 | 15/09/2023 | 09:00 | 17:00 | Y
S1066 | Smith | Matt | 28.50 | 14/09/2023 | 09:00 | 16:30 | N
}

[ Compute Pay > ]

}

@endsalt
